server:
  port: 8876
spring:
  application:
    name: weather
  rabbitmq:
    host: ${mqhost:127.0.0.1}
    port: ${mqport:5672}
    username: ${mquser:rkd}
    password: ${mqpassword:pwd}
    ssl:
      enabled: false
      verify-hostname: false
      validate-server-certificate: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    service-url:
      defaultZone: ${eureka:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: '*'
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  stream:
    queue:
      send-id: false
